-- generated by pyha 0.0.11
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;
    use work.DataValid_0.all;
    use work.DataValid_1.all;
    use work.DataValid_2.all;
    use work.DataValid_3.all;


package DataValid_4 is
    type self_t is record
        data: complex_t(-5 downto -40);
        valid: boolean;
    end record;
    type DataValid_4_self_t_list_t is array (natural range <>) of DataValid_4.self_t;

    type self_t_const is record
        DUMMY: integer;
    end record;
    type DataValid_4_self_t_const_list_t_const is array (natural range <>) of DataValid_4.self_t_const;


    function DataValid(data: complex_t(-5 downto -40); valid: boolean) return self_t;
end package;

package body DataValid_4 is


    function DataValid(data: complex_t(-5 downto -40); valid: boolean) return self_t is
        -- constructor
        variable self: self_t;
    begin
        self.data := data;
        self.valid := valid;
        return self;
    end function;
end package body;
