-- generated by pyha 0.0.7
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;



package DataWithIndex_3 is
    type self_t is record
        data: sfixed(0 downto -17);
        index: integer;
        valid: boolean;
    end record;
    type DataWithIndex_3_self_t_list_t is array (natural range <>) of DataWithIndex_3.self_t;

    type self_t_const is record
        DUMMY: integer;
    end record;
    type DataWithIndex_3_self_t_const_list_t_const is array (natural range <>) of DataWithIndex_3.self_t_const;


    function DataWithIndex(data: sfixed(0 downto -17); index: integer; valid: boolean) return self_t;
end package;

package body DataWithIndex_3 is


    function DataWithIndex(data: sfixed(0 downto -17); index: integer; valid: boolean) return self_t is
        -- limited constructor
        variable self: self_t;
    begin
        self.data := data;
        self.index := index;
        self.valid := valid;
        return self;
    end function;
end package body;
