-- generated by pyha 0.0.10
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;
    use work.DataValid_41.all;
    use work.DataValid_40.all;
    use work.DataValid_39.all;
    use work.DataValid_0.all;


package DataValid_17 is
    type self_t is record
        data: complex_t(-7 downto -42);
        valid: boolean;
    end record;
    type DataValid_17_self_t_list_t is array (natural range <>) of DataValid_17.self_t;

    type self_t_const is record
        DUMMY: integer;
    end record;
    type DataValid_17_self_t_const_list_t_const is array (natural range <>) of DataValid_17.self_t_const;


    function DataValid(data: complex_t(-7 downto -42); valid: boolean) return self_t;
end package;

package body DataValid_17 is


    function DataValid(data: complex_t(-7 downto -42); valid: boolean) return self_t is
        -- constructor
        variable self: self_t;
    begin
        self.data := data;
        self.valid := valid;
        return self;
    end function;
end package body;
