-- generated by pyha 0.0.11
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;
    use work.DataValid_0.all;
    use work.DataValid_1.all;
    use work.DataValid_2.all;
    use work.DataValid_3.all;
    use work.DataValid_4.all;
    use work.DataValid_5.all;
    use work.ShiftRegister_6.all;
    use work.DownCounter_7.all;
    use work.MovingAverage_8.all;
    use work.ShiftRegister_9.all;
    use work.MovingAverage_10.all;
    use work.ShiftRegister_11.all;
    use work.DCRemoval_12.all;
    use work.Windower_13.all;
    use work.ShiftRegister_14.all;
    use work.DownCounter_15.all;
    use work.StageR2SDF_16.all;
    use work.ShiftRegister_17.all;
    use work.DownCounter_18.all;
    use work.StageR2SDF_19.all;
    use work.ShiftRegister_20.all;
    use work.DownCounter_21.all;
    use work.StageR2SDF_22.all;
    use work.DownCounter_23.all;
    use work.StageR2SDF_24.all;
    use work.ShiftRegister_25.all;
    use work.DownCounter_26.all;
    use work.StageR2SDF_27.all;
    use work.ShiftRegister_28.all;
    use work.DownCounter_29.all;
    use work.StageR2SDF_30.all;
    use work.ShiftRegister_31.all;
    use work.DownCounter_32.all;
    use work.StageR2SDF_33.all;
    use work.ShiftRegister_34.all;
    use work.DownCounter_35.all;
    use work.StageR2SDF_36.all;
    use work.ShiftRegister_37.all;
    use work.DownCounter_38.all;
    use work.StageR2SDF_39.all;
    use work.ShiftRegister_40.all;
    use work.DownCounter_41.all;
    use work.StageR2SDF_42.all;
    use work.ShiftRegister_43.all;
    use work.DownCounter_44.all;
    use work.StageR2SDF_45.all;
    use work.ShiftRegister_46.all;
    use work.DownCounter_47.all;
    use work.StageR2SDF_48.all;
    use work.ShiftRegister_49.all;
    use work.StageR2SDF_50.all;
    use work.R2SDF_51.all;

-- FFTPower
-- --------
-- Multiplies complex input by its conjugate: (a + bi)(a - bi) = a**2 + b**2
-- Results in a real number.
package FFTPower_52 is
    type self_t is record
        output: DataValid_5.self_t;
    end record;
    type FFTPower_52_self_t_list_t is array (natural range <>) of FFTPower_52.self_t;

    type self_t_const is record
        output: DataValid_5.self_t_const;
    end record;
    type FFTPower_52_self_t_const_list_t_const is array (natural range <>) of FFTPower_52.self_t_const;

    procedure main(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; input: DataValid_4.self_t; ret_0:out DataValid_5.self_t);
    function FFTPower(output: DataValid_5.self_t) return self_t;
end package;

package body FFTPower_52 is
    procedure main(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; input: DataValid_4.self_t; ret_0:out DataValid_5.self_t) is
    -- Args:
    -- input (DataValid): type not restricted
    -- Returns:
    -- DataValid: Lowest 36 bits from the result.
    -- Example: Input is 18 bits with format 0:-17, then output is 36 bits 1:-34

    begin
        if not input.valid then
            ret_0 := DataValid(self.output.data, valid=>False);
            return;

            -- (a + bi)(a - bi) = a**2 + b**2
        end if;
        self_next.output.data := resize((get_real(input.data) * get_real(input.data)) + (get_imag(input.data) * get_imag(input.data)), -5, -40, fixed_wrap, fixed_truncate);
        self_next.output.valid := input.valid;
        ret_0 := self.output;
        return;
    end procedure;

    function FFTPower(output: DataValid_5.self_t) return self_t is
        -- constructor
        variable self: self_t;
    begin
        self.output := output;
        return self;
    end function;
end package body;
