-- generated by pyha 0.0.11
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;
    use work.DataValid_0.all;
    use work.DataValid_1.all;
    use work.DataValid_2.all;
    use work.DataValid_3.all;
    use work.DataValid_4.all;
    use work.ShiftRegister_5.all;
    use work.DownCounter_6.all;
    use work.MovingAverage_7.all;
    use work.ShiftRegister_8.all;
    use work.MovingAverage_9.all;
    use work.ShiftRegister_10.all;
    use work.DCRemoval_11.all;
    use work.Windower_12.all;
    use work.ShiftRegister_13.all;
    use work.DownCounter_14.all;
    use work.StageR2SDF_15.all;
    use work.ShiftRegister_16.all;
    use work.DownCounter_17.all;
    use work.StageR2SDF_18.all;
    use work.ShiftRegister_19.all;
    use work.DownCounter_20.all;
    use work.StageR2SDF_21.all;
    use work.ShiftRegister_22.all;
    use work.DownCounter_23.all;
    use work.StageR2SDF_24.all;
    use work.ShiftRegister_25.all;
    use work.DownCounter_26.all;
    use work.StageR2SDF_27.all;
    use work.ShiftRegister_28.all;
    use work.DownCounter_29.all;
    use work.StageR2SDF_30.all;
    use work.ShiftRegister_31.all;
    use work.DownCounter_32.all;
    use work.StageR2SDF_33.all;
    use work.ShiftRegister_34.all;
    use work.DownCounter_35.all;
    use work.StageR2SDF_36.all;
    use work.ShiftRegister_37.all;
    use work.StageR2SDF_38.all;
    use work.R2SDF_39.all;
    use work.FFTPower_40.all;

-- Inital values works. No LUTs used if init is all 0, if init is omited some LUTs will be strangely used.
package RAM_41 is
    type self_t is record
        data: Typedefs.sfixed1downto_34_list_t(0 to 511);
        write_value: sfixed(1 downto -34);
        write_enable: boolean;
        write_address: integer;
        read_reg: sfixed(1 downto -34);
        read_address: integer;
    end record;
    type RAM_41_self_t_list_t is array (natural range <>) of RAM_41.self_t;

    type self_t_const is record
        DUMMY: integer;
    end record;
    type RAM_41_self_t_const_list_t_const is array (natural range <>) of RAM_41.self_t_const;

    procedure delayed_read(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; address: integer; ret_0:out sfixed(1 downto -34));
    procedure delayed_write(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; address: integer; value: sfixed(1 downto -34));
    procedure get_readregister(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; ret_0:out sfixed(1 downto -34));
    function RAM(data: Typedefs.sfixed1downto_34_list_t(0 to 511); write_value: sfixed(1 downto -34); write_enable: boolean; write_address: integer; read_reg: sfixed(1 downto -34); read_address: integer) return self_t;
end package;

package body RAM_41 is
    procedure delayed_read(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; address: integer; ret_0:out sfixed(1 downto -34)) is


    begin
        self_next.read_address := address;
        ret_0 := self.read_reg;
        return;
    end procedure;

    procedure delayed_write(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; address: integer; value: sfixed(1 downto -34)) is


    begin
        self_next.write_address := address;
        self_next.write_enable := True;
        self_next.write_value := resize(value, 1, -34, fixed_wrap, fixed_truncate);
    end procedure;

    procedure get_readregister(self:in self_t; self_next:inout self_t; constant self_const: self_t_const; ret_0:out sfixed(1 downto -34)) is


    begin
        ret_0 := self.read_reg;
        return;
    end procedure;

    function RAM(data: Typedefs.sfixed1downto_34_list_t(0 to 511); write_value: sfixed(1 downto -34); write_enable: boolean; write_address: integer; read_reg: sfixed(1 downto -34); read_address: integer) return self_t is
        -- constructor
        variable self: self_t;
    begin
        self.data := data;
        self.write_value := write_value;
        self.write_enable := write_enable;
        self.write_address := write_address;
        self.read_reg := read_reg;
        self.read_address := read_address;
        return self;
    end function;
end package body;
