-- generated by pyha 0.0.7
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.all;

package Typedefs is
    type sfixed0downto_17_list_t is array (natural range <>) of sfixed(0 downto -17);
    type sfixed0downto_7_list_t is array (natural range <>) of sfixed(0 downto -7);
    type complex_t1downto_34_list_t is array (natural range <>) of complex_t(1 downto -34);
    type complex_t1downto_16_list_t is array (natural range <>) of complex_t(1 downto -16);
    type sfixed0downto_35_list_t is array (natural range <>) of sfixed(0 downto -35);
    type integer_list_t is array (natural range <>) of integer;
end package;
