-- generated by pyha 0.0.10
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.complex_pkg.all;
    use work.PyhaUtil.all;
    use work.all;

package Typedefs is
    type complex_t1downto_22_list_t is array (natural range <>) of complex_t(1 downto -22);
    type complex_t1downto_34_list_t is array (natural range <>) of complex_t(1 downto -34);
end package;
